### ISSUE TITLE
All crud tests are failing 

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydrus#239]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

All crud tests either have warnings or they're failing.
```
(hydra) xadahiya@xa-Inspiron-7560:~/hydra/hydrus/hydrus/tests$ python -m unittest test_crud.py 
Creating a temporary datatbsse...
Classes and properties added successfully.
Setup done, running tests...
EEEEEF.EEEEE
======================================================================
ERROR: test_delete (test_crud.TestCRUD)
Test CRUD delete.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 99, in test_delete
    object_=object_, id_=id_, session=self.session)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 145, in insert
    RDFClass.name == object_["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_delete_id (test_crud.TestCRUD)
Test CRUD delete when wrong/undefined ID is given.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 159, in test_delete_id
    object_=object_, id_=id_, session=self.session)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 145, in insert
    RDFClass.name == object_["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_delete_ids (test_crud.TestCRUD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 217, in test_delete_ids
    session=self.session, id_=ids)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 249, in insert_multiple
    RDFClass.name == objects_[index]["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_delete_type (test_crud.TestCRUD)
Test CRUD delete when wrong/undefined class is given.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 143, in test_delete_type
    object_=object_, id_=id_, session=self.session)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 145, in insert
    RDFClass.name == object_["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_get (test_crud.TestCRUD)
Test CRUD get.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 68, in test_get
    response = crud.insert(object_=object_, id_=id_, session=self.session)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 145, in insert
    RDFClass.name == object_["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_insert (test_crud.TestCRUD)
Test CRUD insert.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 61, in test_insert
    response = crud.insert(object_=object_, id_=1, session=self.session)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 145, in insert
    RDFClass.name == object_["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_insert_id (test_crud.TestCRUD)
Test CRUD insert when used ID is given.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 190, in test_insert_id
    object_=object_, id_=id_, session=self.session)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 145, in insert
    RDFClass.name == object_["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 192, in test_insert_id
    response_code, message = e.get_HTTP()
AttributeError: 'TypeError' object has no attribute 'get_HTTP'

======================================================================
ERROR: test_insert_ids (test_crud.TestCRUD)
Test CRUD insert when multiple ID's are given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 205, in test_insert_ids
    objects_=objects, session=self.session, id_=ids)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 249, in insert_multiple
    RDFClass.name == objects_[index]["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 207, in test_insert_ids
    response_code, message = e.get_HTTP()
AttributeError: 'TypeError' object has no attribute 'get_HTTP'

======================================================================
ERROR: test_insert_type (test_crud.TestCRUD)
Test CRUD insert when wrong/undefined class is given.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 174, in test_insert_type
    object_["@type"] = "otherClass"
TypeError: 'NoneType' object does not support item assignment

======================================================================
ERROR: test_update (test_crud.TestCRUD)
Test CRUD update.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 80, in test_update
    object_=object_, id_=id_, session=self.session)
  File "/home/xadahiya/hydra/hydrus/hydrus/data/crud.py", line 145, in insert
    RDFClass.name == object_["@type"]).one()
TypeError: 'NoneType' object is not subscriptable

======================================================================
FAIL: test_get_id (test_crud.TestCRUD)
Test CRUD get when wrong/undefined ID is given.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xadahiya/hydra/hydrus/hydrus/tests/test_crud.py", line 124, in test_get_id
    assert 404 == response_code
AssertionError

----------------------------------------------------------------------
Ran 12 tests in 0.027s

FAILED (failures=1, errors=10)
```
### Expected Behaviour:

All tests should pass
### Steps to reproduce:

Run tests_crud.py using the parser generated doc
### Do you want to work on this issue?
NO

**Comment by xadahiya** [comment]
@vaibhavchellani  Update the tests, use the doc created by parser and please make sure all the tests are passing. Submit a PR with new tests and test logs.

**Comment by vaibhavchellani** [comment]
@xadahiya yes  creating a PR asap

**Comment by vaibhavchellani** [comment]
the issue was that all the test cases are hardcoded for doc_writer_sample and pass the type as "dummyClass" hence the errors and warning , i updated the test to [this](https://gist.github.com/vaibhavchellani/6d6a29c0739236275d34b7fbc48a2ba1) i am able to pass the tests except the warning (which i am looking into) .
<img width="1440" alt="screen shot 2018-07-11 at 12 14 54 am" src="https://user-images.githubusercontent.com/19390504/42530828-d0d1717e-849f-11e8-91b7-b179c0ba6d23.png">

**Comment by xadahiya** [comment]
Okay, create a PR for this. I do have some ideas for improving tests, will write details in the PR.

**Comment by vaibhavchellani** [comment]
@xadahiya should we close this then ?
