### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by de-sh** [HTTP-APIs/hydrus#313]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

```
Creating a temporary database...
going for create doc
Classes and properties added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
....[2018-12-30 12:59:00,076] ERROR in app: Exception on /demoapi/anotherSingleClass [GET]
Traceback (most recent call last):
  File "/bin/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/bin/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/bin/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/bin/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/bin/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "hydrus/hydrus/resources.py", line 256, in get
    path=path)
  File "hydrus/hydrus/data/crud.py", line 561, in get_single
    object_["@id"] = f"/{API_NAME}/{path}"
NameError: name 'API_NAME' is not defined
F.....[2018-12-30 12:59:00,355] ERROR in app: Exception on /demoapi/anotherSingleClass [GET]
Traceback (most recent call last):
  File "/bin/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/bin/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/bin/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/bin/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/bin/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "hydrus/hydrus/resources.py", line 256, in get
    path=path)
  File "hydrus/hydrus/data/crud.py", line 561, in get_single
    object_["@id"] = f"/{API_NAME}/{path}"
NameError: name 'API_NAME' is not defined
F......Creating a temporary datatbase...
Classes, Properties and Users added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
..........Creating a temporary datatbsse...
['User', 'Pet']
User
Classes and properties added successfully.
Setup done, running tests...
.........SELECT EXISTS (SELECT * 
FROM instances 
WHERE instances.id = ?) AS anon_1
.......Importing Open Api Documentation ..
......Method on path /pet/findByStatus already present !
Method on path /pet/findByTags already present !
Method on path /pet/{petId} already present !
Cannot parse path /pet/{petId} because no ref to local class provided
Cannot parse path /pet/{petId} because no ref to local class provided
Cannot parse path /store/inventory because no ref to local class provided
Cannot parse path /store/order/{orderId} because no ref to local class provided
Method on path /user/createWithArray already present !
Method on path /user/createWithList already present !
Cannot parse path /user/login because no ref to local class provided
Cannot parse path /user/logout because no ref to local class provided
Cannot parse path /user/{username} because no ref to local class provided
...
======================================================================
FAIL: test_GET_for_nested_class (hydrus.tests.test_app.ViewsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hydrus/hydrus/tests/test_app.py", line 381, in test_GET_for_nested_class
    assert response_get.status_code == 200
AssertionError

======================================================================
FAIL: test_endpointClass_GET (hydrus.tests.test_app.ViewsTestCase)
Check non collection Class GET.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hydrus/hydrus/tests/test_app.py", line 360, in test_endpointClass_GET
    assert response_get.status_code == 200
AssertionError

----------------------------------------------------------------------
Ran 52 tests in 1.361s

FAILED (failures=2)
```
I am using Pipenv with the version of venv python is 3.6
(Why is there a NameError?)

### Expected Behaviour:

Runs without assertion error and `API_NAME` is found to be defined.

### Steps to reproduce:

Starting from codebase after #311 
```
pipenv install
pipenv run python -m unittest discover
```

### Do you want to work on this issue?

YES!

**Comment by de-sh** [comment]
Found out the error was because of my own mistake, sorry for the unnecessary issue
